#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
	selected=$1
else
	# selected=$(fd -td --hidden --require-git --exclude node_modules --exclude .cargo --exclude .quokka --exclude .rustup --exclude .nuget --search-path ~/ | fzf)
	selected=$(fd -td --require-git --exclude node_modules --exclude .cargo --exclude .quokka --exclude .rustup --exclude .nuget --search-path ~/ | fzf)
	# selected=$(fd -td --hidden --require-git --search-path ~/main | fzf)
fi

if [[ -z $selected ]]; then
	exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
	tmux new-session -s $selected_name -c $selected
	exit 0
fi

if ! tmux has-session -t=$selected_name 2>/dev/null; then
	tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
