#!/bin/bash

# delete all gemini sessions (instead of manually ctrl+b+s then x to delete)
# name of sessions: gemini*
#

# query all sessions with gemini* as their "name"
# loop then delete those
#
# NOTE: one-liner in cli --> tmux kill-session -t "$(tmux ls | grep "gemini*" | cut -d':' -f1 | fzf)"

if [[ $# -eq 1 ]]; then
    selected=$1
else
    # gemini_sessions=$(tmux ls | grep "gemini*" | cut -d':' -f1)
    # selected=$(echo "$gemini_sessions" | fzf --tmux --prompt="to delete: > ")
    all_sessions=$(tmux ls | cut -d':' -f1)
    selected=$(echo "$all_sessions" | fzf -m --layout=reverse-list --prompt="to delete (tab - select multiple): > " --color="prompt:red,border:red" --preview="tmux list-windows -t '{}'" --preview-window="right:wrap")
fi

# if session is not selected (empty, did not select anything in fzf), then exit
if [[ -z $selected ]]; then
    exit 0
fi

# can select multiple (via fzf -m) with <TAB> and unselect with <Shift-TAB>
echo "$selected" | while read -r session; do
    tmux kill-session -t "$session"
done
