#!/usr/bin/env bash
# TODO: error handling things

# symlink nvim
# TODO: add a backup for nvim config (see LazyVim docs)
ln -s ~/dotfiles/nvim ~/.config/nvim

# symlink tmux
ln -s ~/dotfiles/tmux ~/.tmux
ln -s ~/dotfiles/tmux/.tmux.conf ~/.tmux.conf
tmux source ~/.tmux.conf

# symlink home configs
mv ~/.zshrc ~/.zshrc.bak
mv ~/.ideavimrc ~/.ideavimrc.bak
ln -s ~/dotfiles/.zshrc ~/.zshrc
ln -s ~/dotfiles/.ideavimrc ~/.ideavimrc

# symlink bspwm configs
mv ~/.config/bspwm/bspwmrc ~/.config/bspwm/bspwmrc.bak
mv ~/.config/bspwm/sxhkdrc ~/.config/bspwm/sxhkdrc.bak
ln -s ~/dotfiles/config/bspwm/bspwmrc ~/.config/bspwm/bspwmrc
ln -s ~/dotfiles/config/bspwm/sxhkdrc ~/.config/bspwm/sxhkdrc

# TODO: print message (instructions) to install nvim plugins and tmux
# open nvim to install plugins
# open tmux to install plugins via prefix + I
