#!/usr/bin/env bash
# TODO: error handling things

# symlink nvim
# TODO: add a backup for nvim config (see LazyVim docs)
ln -s ~/dotfiles/nvim ~/.config/

# symlink tmux
ln -s ~/dotfiles/tmux ~/
ln -s ~/dotfiles/tmux/.tmux.conf ~/
tmux source ~/.tmux.conf

# symlink home configs
mv ~/.zshrc ~/.zshrc.bak
mv ~/.ideavimrc ~/.ideavimrc.bak
mv ~/.vimrc ~/.vimrc.bak
ln -s ~/dotfiles/.zshrc ~/
ln -s ~/dotfiles/.ideavimrc ~/
ln -s ~/dotfiles/.vimrc ~/

# symlink bspwm configs
mv ~/.config/bspwm/bspwmrc ~/.config/bspwm/bspwmrc.bak
mv ~/.config/bspwm/sxhkdrc ~/.config/bspwm/sxhkdrc.bak
ln -s ~/dotfiles/config/bspwm/bspwmrc ~/.config/bspwm/
ln -s ~/dotfiles/config/bspwm/sxhkdrc ~/.config/bspwm/

mv ~/.mozilla/firefox/*.default-release/chrome ~/.mozilla/firefox/*.default-release/chrome_backup
mv ~/.mozilla/firefox/*.default-release/user.js ~/.mozilla/firefox/*.default-release/user.js.bak
ln -s ~/dotfiles/misc/firefox/chrome ~/.mozilla/firefox/*.default-release/
ln -s ~/dotfiles/misc/firefox/user.js ~/.mozilla/firefox/*.default-release/

# TODO: print message (instructions) to install nvim plugins and tmux
# open nvim to install plugins
# open tmux to install plugins via prefix + I
