#!/usr/bin/env bash
# Generated from dotfiles/kde/ — portable subset only.
# Skips machine-specific UUIDs: kwinrc Desktops Id_*, Tiling[desktop][output],
# kglobalshortcutsrc ActivityManager switch-to-activity-*.
# Spectacle launch keys ARE here ([services][org.kde.spectacle.desktop]) —
# spectaclerc itself only stores save-path/quality, not needed for keybinds.
# Usage: ./apply-kde-config.sh
set -euo pipefail

# --- kwinrc: Desktops (names/count only, IDs are per-install) ----
kwriteconfig6 --file kwinrc --group Desktops --key Name_1 'WEB'
kwriteconfig6 --file kwinrc --group Desktops --key Name_2 'TERM'
kwriteconfig6 --file kwinrc --group Desktops --key Number 2
kwriteconfig6 --file kwinrc --group Desktops --key Rows 1

# --- kwinrc: effects/plugins ----
kwriteconfig6 --file kwinrc --group Effect-mousemark --key Arrowdrawalt true
kwriteconfig6 --file kwinrc --group Effect-mousemark --key Color '255,255,255'
kwriteconfig6 --file kwinrc --group Effect-mousemark --key Freedrawcontrol true
kwriteconfig6 --file kwinrc --group Plugins --key blurEnabled true
kwriteconfig6 --file kwinrc --group Plugins --key krohnkiteEnabled false
kwriteconfig6 --file kwinrc --group Plugins --key mousemarkEnabled true
kwriteconfig6 --file kwinrc --group Plugins --key slideEnabled false
kwriteconfig6 --file kwinrc --group Plugins --key synchronizeskipswitcherEnabled false
kwriteconfig6 --file kwinrc --group Plugins --key wobblywindowsEnabled true

# --- kwinrc: Wayland / Windows / Xwayland ----
# NOTE:: VirtualKeyboardMode=1 (NonMouseInput) as stored; use 0 to fully disable
kwriteconfig6 --file kwinrc --group Wayland --key VirtualKeyboardMode 1
kwriteconfig6 --file kwinrc --group Windows --key RollOverDesktops true
kwriteconfig6 --file kwinrc --group Xwayland --key Scale 1

# --- kglobalshortcutsrc: KDE Keyboard Layout Switcher ----
kwriteconfig6 --file kglobalshortcutsrc --group 'KDE Keyboard Layout Switcher' --key 'Switch to Last-Used Keyboard Layout' 'Meta+Alt+L,Meta+Alt+L,Switch to Last-Used Keyboard Layout'
kwriteconfig6 --file kglobalshortcutsrc --group 'KDE Keyboard Layout Switcher' --key 'Switch to Next Keyboard Layout' 'Meta+Alt+K,Meta+Alt+K,Switch to Next Keyboard Layout'

# --- kglobalshortcutsrc: kaccess ----
kwriteconfig6 --file kglobalshortcutsrc --group kaccess --key 'Toggle Screen Reader On and Off' 'Meta+Alt+S,Meta+Alt+S,Toggle Screen Reader On and Off'

# --- kglobalshortcutsrc: kmix ----
kwriteconfig6 --file kglobalshortcutsrc --group kmix --key decrease_microphone_volume 'Microphone Volume Down,Microphone Volume Down,Decrease Microphone Volume'
kwriteconfig6 --file kglobalshortcutsrc --group kmix --key decrease_volume 'Volume Down,Volume Down,Decrease Volume'
kwriteconfig6 --file kglobalshortcutsrc --group kmix --key decrease_volume_small 'Shift+Volume Down,Shift+Volume Down,Decrease Volume by 1%'
kwriteconfig6 --file kglobalshortcutsrc --group kmix --key increase_microphone_volume 'Microphone Volume Up,Microphone Volume Up,Increase Microphone Volume'
kwriteconfig6 --file kglobalshortcutsrc --group kmix --key increase_volume 'Volume Up,Volume Up,Increase Volume'
kwriteconfig6 --file kglobalshortcutsrc --group kmix --key increase_volume_small 'Shift+Volume Up,Shift+Volume Up,Increase Volume by 1%'
kwriteconfig6 --file kglobalshortcutsrc --group kmix --key mic_mute 'Microphone Mute\tMeta+`\tMeta+Volume Mute,Microphone Mute\tMeta+Volume Mute,Mute Microphone'
kwriteconfig6 --file kglobalshortcutsrc --group kmix --key mute 'Volume Mute,Volume Mute,Mute'
kwriteconfig6 --file kglobalshortcutsrc --group kmix --key push_to_talk 'none,none,Push to talk'

# --- kglobalshortcutsrc: ksmserver ----
kwriteconfig6 --file kglobalshortcutsrc --group ksmserver --key 'Halt Without Confirmation' 'none,none,Shut Down Without Confirmation'
kwriteconfig6 --file kglobalshortcutsrc --group ksmserver --key 'Lock Session' 'Screensaver\tMeta+Ctrl+Alt+L,Screensaver\tMeta+L,Lock Session'
kwriteconfig6 --file kglobalshortcutsrc --group ksmserver --key 'Log Out' 'Ctrl+Alt+Del,Ctrl+Alt+Del,Show Logout Screen'
kwriteconfig6 --file kglobalshortcutsrc --group ksmserver --key 'Log Out Without Confirmation' 'none,none,Log Out Without Confirmation'
kwriteconfig6 --file kglobalshortcutsrc --group ksmserver --key LogOut 'none,none,Log Out'
kwriteconfig6 --file kglobalshortcutsrc --group ksmserver --key Reboot 'Meta+Ctrl+Alt+R,none,Reboot'
kwriteconfig6 --file kglobalshortcutsrc --group ksmserver --key 'Reboot Without Confirmation' 'none,none,Reboot Without Confirmation'
kwriteconfig6 --file kglobalshortcutsrc --group ksmserver --key 'Shut Down' 'Meta+Ctrl+Alt+S,none,Shut Down'

# --- kglobalshortcutsrc: kwin ----
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Activate Window Demanding Attention' 'Meta+Ctrl+A,Meta+Ctrl+A,Activate Window Demanding Attention'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key ClearLastMouseMark 'Meta+F12\tMeta+Ctrl+Shift+Z,Meta+Shift+F12,Clear Last Mouse Mark'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key ClearMouseMarks 'Meta+F11\tMeta+Ctrl+Shift+X,Meta+Shift+F11,Clear All Mouse Marks'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Cycle Overview' 'none,none,Cycle through Overview and Grid View'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Cycle Overview Opposite' 'none,none,Cycle through Grid View and Overview'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Decrease Opacity' 'none,none,Decrease Opacity of Active Window by 5%'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Edit Tiles' 'none,Meta+T,Toggle Tiles Editor'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key Expose 'Ctrl+F9,Ctrl+F9\tMeta+F9,Toggle Present Windows (Current desktop)'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key ExposeAll 'Launch (C)\tCtrl+F10,Launch (C)\tCtrl+F10\tMeta+F10,Toggle Present Windows (All desktops)'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key ExposeClass 'Ctrl+F7,Ctrl+F7\tMeta+F7,Toggle Present Windows (Window class)'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key ExposeClassCurrentDesktop 'none,none,Toggle Present Windows (Window class on current desktop)'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Grid View' 'Meta+G,Meta+G,Toggle Grid View'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Increase Opacity' 'none,none,Increase Opacity of Active Window by 5%'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Kill Window' 'Meta+Ctrl+Esc,Meta+Ctrl+Esc,Kill Window'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Move Tablet to Next LogicalOutput' 'none,none,Move the tablet to the next output'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key MoveMouseToCenter 'Meta+F6,Meta+F6,Move Mouse to Center'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key MoveMouseToFocus 'Meta+F5,Meta+F5,Move Mouse to Focus'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key MoveZoomDown 'none,none,Move Zoomed Area Downwards'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key MoveZoomLeft 'none,none,Move Zoomed Area to Left'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key MoveZoomRight 'none,none,Move Zoomed Area to Right'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key MoveZoomUp 'none,none,Move Zoomed Area Upwards'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key Overview 'Meta+W,Meta+W,Toggle Overview'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Setup Window Shortcut' 'none,none,Setup Window Shortcut'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Show Desktop' 'Meta+D,Meta+D,Peek at Desktop'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch One Desktop Down' 'Meta+Ctrl+Down,Meta+Ctrl+Down,Switch One Desktop Down'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch One Desktop Up' 'Meta+Ctrl+Up,Meta+Ctrl+Up,Switch One Desktop Up'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch One Desktop to the Left' 'Meta+Ctrl+Left,Meta+Ctrl+Left,Switch One Desktop to the Left'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch One Desktop to the Right' 'Meta+Ctrl+Right,Meta+Ctrl+Right,Switch One Desktop to the Right'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch Window Down' 'Meta+Alt+Down,Meta+Alt+Down,Switch to Window Below'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch Window Left' 'Meta+Alt+Left,Meta+Alt+Left,Switch to Window to the Left'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch Window Right' 'Meta+Alt+Right,Meta+Alt+Right,Switch to Window to the Right'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch Window Up' 'Meta+Alt+Up,Meta+Alt+Up,Switch to Window Above'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Desktop 1' 'Ctrl+F1\tMeta+1,Ctrl+F1\tMeta+F1,Switch to Desktop 1'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Desktop 10' 'none,none,Switch to Desktop 10'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Desktop 11' 'none,none,Switch to Desktop 11'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Desktop 12' 'none,none,Switch to Desktop 12'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Desktop 13' 'none,none,Switch to Desktop 13'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Desktop 14' 'none,none,Switch to Desktop 14'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Desktop 15' 'none,none,Switch to Desktop 15'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Desktop 16' 'none,none,Switch to Desktop 16'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Desktop 17' 'none,none,Switch to Desktop 17'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Desktop 18' 'none,none,Switch to Desktop 18'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Desktop 19' 'none,none,Switch to Desktop 19'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Desktop 2' 'Ctrl+F2\tMeta+2,Ctrl+F2\tMeta+F2,Switch to Desktop 2'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Desktop 20' 'none,none,Switch to Desktop 20'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Desktop 21' 'none,none,Switch to Desktop 21'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Desktop 22' 'none,none,Switch to Desktop 22'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Desktop 23' 'none,none,Switch to Desktop 23'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Desktop 24' 'none,none,Switch to Desktop 24'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Desktop 25' 'none,none,Switch to Desktop 25'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Desktop 3' 'Ctrl+F3,Ctrl+F3\tMeta+F3,Switch to Desktop 3'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Desktop 4' 'Ctrl+F4,Ctrl+F4\tMeta+F4,Switch to Desktop 4'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Desktop 5' 'none,none,Switch to Desktop 5'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Desktop 6' 'none,none,Switch to Desktop 6'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Desktop 7' 'none,none,Switch to Desktop 7'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Desktop 8' 'none,none,Switch to Desktop 8'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Desktop 9' 'none,none,Switch to Desktop 9'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Next Desktop' 'Meta+Tab,none,Switch to Next Desktop'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Next Screen' 'none,none,Switch to Next Screen'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Previous Desktop' 'none,none,Switch to Previous Desktop'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Previous Screen' 'none,none,Switch to Previous Screen'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Screen 0' 'none,none,Switch to Screen 0'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Screen 1' 'none,none,Switch to Screen 1'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Screen 2' 'none,none,Switch to Screen 2'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Screen 3' 'none,none,Switch to Screen 3'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Screen 4' 'none,none,Switch to Screen 4'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Screen 5' 'none,none,Switch to Screen 5'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Screen 6' 'none,none,Switch to Screen 6'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Screen 7' 'none,none,Switch to Screen 7'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Screen Above' 'none,none,Switch to Screen Above'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Screen Below' 'none,none,Switch to Screen Below'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Screen to the Left' 'none,none,Switch to Screen to the Left'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Switch to Screen to the Right' 'none,none,Switch to Screen to the Right'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Toggle Night Color' 'none,none,Suspend/Resume Night Light'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Toggle Window Raise/Lower' 'none,none,Toggle Window Raise/Lower'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Walk Through Windows' 'Alt+Tab,Alt+Tab\tMeta+Tab,Walk Through Windows'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Walk Through Windows (Reverse)' 'Alt+Shift+Tab,Alt+Shift+Tab\tMeta+Shift+Tab,Walk Through Windows (Reverse)'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Walk Through Windows Alternative' 'none,none,Walk Through Windows Alternative'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Walk Through Windows Alternative (Reverse)' 'none,none,Walk Through Windows Alternative (Reverse)'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Walk Through Windows of Current Application' 'Alt+`,Alt+`\tMeta+`,Walk Through Windows of Current Application'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Walk Through Windows of Current Application (Reverse)' 'Alt+~,Alt+~\tMeta+~,Walk Through Windows of Current Application (Reverse)'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Walk Through Windows of Current Application Alternative' 'none,none,Walk Through Windows of Current Application Alternative'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Walk Through Windows of Current Application Alternative (Reverse)' 'none,none,Walk Through Windows of Current Application Alternative (Reverse)'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Above Other Windows' 'none,none,Keep Window Above Others'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Below Other Windows' 'none,none,Keep Window Below Others'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Close' 'Alt+F4\tMeta+Q,Alt+F4,Close Window'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Custom Quick Tile Bottom' 'none,none,Custom Quick Tile Window to the Bottom'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Custom Quick Tile Left' 'none,none,Custom Quick Tile Window to the Left'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Custom Quick Tile Right' 'none,none,Custom Quick Tile Window to the Right'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Custom Quick Tile Top' 'none,none,Custom Quick Tile Window to the Top'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Fullscreen' 'none,none,Make Window Fullscreen'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Grow Horizontal' 'none,none,Expand Window Horizontally'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Grow Vertical' 'none,none,Expand Window Vertically'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Lower' 'none,none,Lower Window'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Maximize' 'Meta+A\tMeta+PgUp,Meta+PgUp,Maximize Window'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Maximize Horizontal' 'none,none,Maximize Window Horizontally'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Maximize Vertical' 'none,none,Maximize Window Vertically'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Minimize' 'Meta+S\tMeta+PgDown,Meta+PgDown,Minimize Window'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Move' 'none,none,Move Window'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Move Center' 'none,none,Move Window to the Center'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window No Border' 'none,none,Toggle Window Titlebar and Frame'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window On All Desktops' 'none,none,Keep Window on All Desktops'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window One Desktop Down' 'Meta+Ctrl+Shift+Down,Meta+Ctrl+Shift+Down,Window One Desktop Down'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window One Desktop Up' 'Meta+Ctrl+Shift+Up,Meta+Ctrl+Shift+Up,Window One Desktop Up'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window One Desktop to the Left' 'Meta+Ctrl+Shift+Left,Meta+Ctrl+Shift+Left,Window One Desktop to the Left'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window One Desktop to the Right' 'Meta+Ctrl+Shift+Right,Meta+Ctrl+Shift+Right,Window One Desktop to the Right'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window One Screen Down' 'none,none,Move Window One Screen Down'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window One Screen Up' 'none,none,Move Window One Screen Up'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window One Screen to the Left' 'none,none,Move Window One Screen to the Left'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window One Screen to the Right' 'none,none,Move Window One Screen to the Right'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Operations Menu' 'Alt+F3,Alt+F3,Window Menu'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Pack Down' 'none,none,Move Window Down'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Pack Left' 'none,none,Move Window Left'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Pack Right' 'none,none,Move Window Right'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Pack Up' 'none,none,Move Window Up'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Quick Tile Bottom' 'Meta+Down,Meta+Down,Quick Tile Window to the Bottom'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Quick Tile Bottom Left' 'none,none,Quick Tile Window to the Bottom Left'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Quick Tile Bottom Right' 'none,none,Quick Tile Window to the Bottom Right'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Quick Tile Left' 'Meta+Left,Meta+Left,Quick Tile Window to the Left'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Quick Tile Right' 'Meta+Right,Meta+Right,Quick Tile Window to the Right'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Quick Tile Top' 'Meta+Up,Meta+Up,Quick Tile Window to the Top'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Quick Tile Top Left' 'none,none,Quick Tile Window to the Top Left'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Quick Tile Top Right' 'none,none,Quick Tile Window to the Top Right'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Raise' 'none,none,Raise Window'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Resize' 'none,none,Resize Window'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Restore' 'Meta+Backspace,Meta+Backspace,Restore Window'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Shrink Horizontal' 'none,none,Shrink Window Horizontally'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window Shrink Vertical' 'none,none,Shrink Window Vertically'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Desktop 1' 'Meta+!,none,Window to Desktop 1'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Desktop 10' 'none,none,Window to Desktop 10'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Desktop 11' 'none,none,Window to Desktop 11'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Desktop 12' 'none,none,Window to Desktop 12'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Desktop 13' 'none,none,Window to Desktop 13'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Desktop 14' 'none,none,Window to Desktop 14'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Desktop 15' 'none,none,Window to Desktop 15'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Desktop 16' 'none,none,Window to Desktop 16'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Desktop 17' 'none,none,Window to Desktop 17'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Desktop 18' 'none,none,Window to Desktop 18'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Desktop 19' 'none,none,Window to Desktop 19'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Desktop 2' 'Meta+@,none,Window to Desktop 2'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Desktop 20' 'none,none,Window to Desktop 20'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Desktop 21' 'none,none,Window to Desktop 21'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Desktop 22' 'none,none,Window to Desktop 22'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Desktop 23' 'none,none,Window to Desktop 23'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Desktop 24' 'none,none,Window to Desktop 24'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Desktop 25' 'none,none,Window to Desktop 25'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Desktop 3' 'none,none,Window to Desktop 3'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Desktop 4' 'none,none,Window to Desktop 4'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Desktop 5' 'none,none,Window to Desktop 5'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Desktop 6' 'none,none,Window to Desktop 6'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Desktop 7' 'none,none,Window to Desktop 7'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Desktop 8' 'none,none,Window to Desktop 8'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Desktop 9' 'none,none,Window to Desktop 9'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Next Desktop' 'none,none,Window to Next Desktop'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Next Screen' 'Meta+Shift+Right,Meta+Shift+Right,Move Window to Next Screen'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Previous Desktop' 'none,none,Window to Previous Desktop'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Previous Screen' 'Meta+Shift+Left,Meta+Shift+Left,Move Window to Previous Screen'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Screen 0' 'none,none,Move Window to Screen 0'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Screen 1' 'none,none,Move Window to Screen 1'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Screen 2' 'none,none,Move Window to Screen 2'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Screen 3' 'none,none,Move Window to Screen 3'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Screen 4' 'none,none,Move Window to Screen 4'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Screen 5' 'none,none,Move Window to Screen 5'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Screen 6' 'none,none,Move Window to Screen 6'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key 'Window to Screen 7' 'none,none,Move Window to Screen 7'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key disableInputCapture 'Meta+Shift+Esc,Meta+Shift+Esc,Disable Active Input Capture'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key view_actual_size 'Meta+0,Meta+0,Zoom to Actual Size'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key view_zoom_in 'Meta++\tMeta+=,Meta++\tMeta+=,Zoom In'
kwriteconfig6 --file kglobalshortcutsrc --group kwin --key view_zoom_out 'Meta+-,Meta+-,Zoom Out'

# --- kglobalshortcutsrc: mediacontrol ----
kwriteconfig6 --file kglobalshortcutsrc --group mediacontrol --key mediavolumedown 'none,none,Media volume down'
kwriteconfig6 --file kglobalshortcutsrc --group mediacontrol --key mediavolumeup 'none,none,Media volume up'
kwriteconfig6 --file kglobalshortcutsrc --group mediacontrol --key nextmedia 'Media Next,Media Next,Media playback next'
kwriteconfig6 --file kglobalshortcutsrc --group mediacontrol --key pausemedia 'Media Pause,Media Pause,Pause media playback'
kwriteconfig6 --file kglobalshortcutsrc --group mediacontrol --key playmedia 'none,none,Play media playback'
kwriteconfig6 --file kglobalshortcutsrc --group mediacontrol --key playpausemedia 'Media Play,Media Play,Play/Pause media playback'
kwriteconfig6 --file kglobalshortcutsrc --group mediacontrol --key previousmedia 'Media Previous,Media Previous,Media playback previous'
kwriteconfig6 --file kglobalshortcutsrc --group mediacontrol --key seekbackwardmedia 'Media Rewind,Media Rewind,Media playback seek backward 5s'
kwriteconfig6 --file kglobalshortcutsrc --group mediacontrol --key seekbackwardmedialong 'none,none,Media playback seek backward 30s'
kwriteconfig6 --file kglobalshortcutsrc --group mediacontrol --key seekforwardmedia 'Media Fast Forward,Media Fast Forward,Media playback seek forward 5s'
kwriteconfig6 --file kglobalshortcutsrc --group mediacontrol --key seekforwardmedialong 'none,none,Media playback seek forward 30s'
kwriteconfig6 --file kglobalshortcutsrc --group mediacontrol --key stopmedia 'Media Stop,Media Stop,Stop media playback'

# --- kglobalshortcutsrc: org_kde_powerdevil ----
kwriteconfig6 --file kglobalshortcutsrc --group org_kde_powerdevil --key 'Decrease Keyboard Brightness' 'Keyboard Brightness Down,Keyboard Brightness Down,Decrease Keyboard Brightness'
kwriteconfig6 --file kglobalshortcutsrc --group org_kde_powerdevil --key 'Decrease Screen Brightness' 'Monitor Brightness Down,Monitor Brightness Down,Decrease Screen Brightness'
kwriteconfig6 --file kglobalshortcutsrc --group org_kde_powerdevil --key 'Decrease Screen Brightness Small' 'Shift+Monitor Brightness Down,Shift+Monitor Brightness Down,Decrease Screen Brightness by 1%'
kwriteconfig6 --file kglobalshortcutsrc --group org_kde_powerdevil --key Hibernate 'Hibernate,Hibernate,Hibernate'
kwriteconfig6 --file kglobalshortcutsrc --group org_kde_powerdevil --key 'Increase Keyboard Brightness' 'Keyboard Brightness Up,Keyboard Brightness Up,Increase Keyboard Brightness'
kwriteconfig6 --file kglobalshortcutsrc --group org_kde_powerdevil --key 'Increase Screen Brightness' 'Monitor Brightness Up,Monitor Brightness Up,Increase Screen Brightness'
kwriteconfig6 --file kglobalshortcutsrc --group org_kde_powerdevil --key 'Increase Screen Brightness Small' 'Shift+Monitor Brightness Up,Shift+Monitor Brightness Up,Increase Screen Brightness by 1%'
kwriteconfig6 --file kglobalshortcutsrc --group org_kde_powerdevil --key PowerDown 'Power Down,Power Down,Power Down'
kwriteconfig6 --file kglobalshortcutsrc --group org_kde_powerdevil --key PowerOff 'Power Off,Power Off,Power Off'
kwriteconfig6 --file kglobalshortcutsrc --group org_kde_powerdevil --key Sleep 'Sleep,Sleep,Suspend'
kwriteconfig6 --file kglobalshortcutsrc --group org_kde_powerdevil --key 'Toggle Keyboard Backlight' 'Keyboard Light On/Off,Keyboard Light On/Off,Toggle Keyboard Backlight'
kwriteconfig6 --file kglobalshortcutsrc --group org_kde_powerdevil --key 'Turn Off Screen' 'none,none,Turn Off Screen'
kwriteconfig6 --file kglobalshortcutsrc --group org_kde_powerdevil --key powerProfile 'Battery\tMeta+B,Battery\tMeta+B,Switch Power Profile'

# --- kglobalshortcutsrc: plasmashell ----
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key 'Slideshow Wallpaper Next Image' 'none,none,Next Wallpaper Image'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key 'activate application launcher' 'Meta\tAlt+F1,Meta\tAlt+F1,Activate Application Launcher'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key 'activate task manager entry 1' 'none,Meta+1,Activate Task Manager Entry 1'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key 'activate task manager entry 10' 'none,none,Activate Task Manager Entry 10'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key 'activate task manager entry 2' 'none,Meta+2,Activate Task Manager Entry 2'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key 'activate task manager entry 3' 'Meta+3,Meta+3,Activate Task Manager Entry 3'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key 'activate task manager entry 4' 'Meta+4,Meta+4,Activate Task Manager Entry 4'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key 'activate task manager entry 5' 'Meta+5,Meta+5,Activate Task Manager Entry 5'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key 'activate task manager entry 6' 'Meta+6,Meta+6,Activate Task Manager Entry 6'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key 'activate task manager entry 7' 'Meta+7,Meta+7,Activate Task Manager Entry 7'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key 'activate task manager entry 8' 'Meta+8,Meta+8,Activate Task Manager Entry 8'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key 'activate task manager entry 9' 'Meta+9,Meta+9,Activate Task Manager Entry 9'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key 'activate widget 34' 'none,none,Activate Window List Widget'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key 'clear history' 'none,none,Clear Notification History'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key clear-history 'none,none,Clear Clipboard History'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key clipboard_action 'Meta+Ctrl+X,Meta+Ctrl+X,Automatic Action Popup Menu'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key cycle-panels 'Meta+Alt+P,Meta+Alt+P,Move keyboard focus between panels'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key cycleNextAction 'none,none,Next History Item'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key cyclePrevAction 'none,none,Previous History Item'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key edit_clipboard 'none,none,Edit Contents…'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key 'manage activities' 'none,Meta+Q,Show Activity Switcher'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key 'next activity' 'none,none,Walk through activities'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key 'previous activity' 'Meta+Shift+A,none,Walk through activities (Reverse)'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key repeat_action 'none,none,Manually Invoke Action on Current Clipboard'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key 'show dashboard' 'Ctrl+F12,Ctrl+F12,Show Desktop'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key show-barcode 'none,none,Show Barcode…'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key show-on-mouse-pos 'Meta+V,Meta+V,Show Clipboard Items at Mouse Position'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key 'switch to next activity' 'none,none,Switch to Next Activity'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key 'switch to previous activity' 'none,none,Switch to Previous Activity'
kwriteconfig6 --file kglobalshortcutsrc --group plasmashell --key 'toggle do not disturb' 'Meta+:,none,Toggle do not disturb'

# --- kglobalshortcutsrc: app launches (incl. Spectacle — no spectaclerc needed) ----
kwriteconfig6 --file kglobalshortcutsrc --group services --group com.mitchellh.ghostty.desktop --key _launch 'Meta+T'
kwriteconfig6 --file kglobalshortcutsrc --group services --group org.kde.spectacle.desktop --key FullScreenScreenShot 'Shift+Print\tMeta+Shift+D'
kwriteconfig6 --file kglobalshortcutsrc --group services --group org.kde.spectacle.desktop --key RectangularRegionScreenShot 'Meta+Shift+S\tMeta+Shift+Print'
kwriteconfig6 --file kglobalshortcutsrc --group services --group org.kde.spectacle.desktop --key _launch 'none'
kwriteconfig6 --file kglobalshortcutsrc --group services --group org.mozilla.firefox.desktop --key _launch 'Meta+F'
kwriteconfig6 --file kglobalshortcutsrc --group services --group systemsettings.desktop --key _launch 'Tools'

# --- apply live ----
# ponytail: qdbus6 missing on Fedora, qdbus-qt6 is the Plasma 6 bus tool
QDBUS="$(command -v qdbus6 || command -v qdbus-qt6 || command -v qdbus)"
"$QDBUS" org.kde.KWin /KWin reconfigure || true
# ponytail: kglobalaccel has no reconfigure method on Plasma 6 (verified via introspection) — restart re-reads kglobalshortcutsrc
systemctl --user restart plasma-kglobalaccel.service || true
