#!/bin/bash

# Script to create new DNS A record and associated PTR Record
# NOTE: --> needs /etc/bind/
#
# ref: https://github.com/Danshaw509/publicscripts/blob/main/new-record.sh

# Get Hostname and IP Address
hostname=$1
ip=$2

if [ -z "$hostname" ]; then
	echo ""
	read -p "Please enter new DNS Record's hostname" hostname
fi

if [ -z "$ip" ]; then
	echo ""
	read -p "Please enter new DNS Record's ip address" ip
fi

# A Record Creation
echo -en $"\n$hostname     IN  A  $ip" >>/etc/bind/zones/example.com

# PTR Record Creation
if [[ $ip == "10.0.0"* ]]; then
	ReverseZone="10.0.0.0-reverse"
else
	ReverseZone="10.0.4.0-reverse"
fi

# Get last octet of ip address for ptr record
ReverseIP=$(echo $ip | sed 's/.*[^0-9]\(.*\)$/\1/')

# Create reverse record in identified zone
echo -en $"\n$ReverseIP    IN  PTR  $hostname.example.com." >>/etc/bind/zones/$ReverseZone

# Apply Changes
/etc/bind/scripts/deploy.sh

# Verify Record Creation
echo "Forward Record Lookup"
nslookup $hostname
