#!/bin/bash

# TODO: clean this

######## check Lock-encrypt: ########
lock_encrypt_file=$(find "$usb_mountpoint" -type f -name "Lock-encrypt.tar.gz.gpg")
if [ -n "$lock_encrypt_file" ]; then
	echo "[ AUTHENTICATE ] Decrypting Lock-encrypt directory..."
	gpg -d -o - "$lock_encrypt_file" | pv -ptrb --size "$(du -sb "$lock_encrypt_file" | awk '{print $1}')" | sudo tar xzf - || {
		echo "[ ERROR ] Failed to decrypt Lock-encrypt directory."
		exit 1
	}
fi
########################

echo "[ AUTHENTICATE ] Encrypting Lock-encrypt directory..."
sudo tar czf - "$usb_mountpoint"/Lock-encrypt | pv -ptrb --size "$(du -sb "$usb_mountpoint"/Lock-encrypt | awk '{print $1}')" | sudo gpg --symmetric -o "$usb_mountpoint"/Lock-encrypt.tar.gz.gpg || {
	echo "[ ERROR ] Failed to encrypt Lock-encrypt directory."
	exit 1
}

printf "[ WARNING ] Lock-encrypt directory will be removed from USB."
while true; do
	read -rp " Do you wish to continue? [y/N]: " yn
	case $yn in
	[Yy]*)
		echo "[ REMOVING ] Lock-encrypt directory..."
		sudo rm -rf "$usb_mountpoint"/Lock-encrypt
		;;
	[Nn]*)
		echo "[ SKIPPING ] Lock-encrypt directory will not be removed."
		break
		;;
	*) printf " Error: only write 'y' or 'n'\n\n" ;;
	esac
done
