#!/bin/bash

network_ids=$(docker network ls --format '{{.ID}}') # docker network ls --format 'json' | jq '.ID' or docker netowrk ls -q

for network_id in $network_ids; do
    network_name=$(docker network inspect --format '{{.Name}}' "$network_id") # get network name

    # get ipv4 addresses
    ipv4_address=$(docker network inspect --format '{{range .IPAM.Config}}{{.Subnet}}{{end}}' "$network_id")

    echo "Network Name: $network_name"
    echo "IPv4 Address: $ipv4_address"
    echo "--------------------------------------"
done
