#!/bin/bash

# TODO: add colors for dramatic effects kekw

if [ -z "$1" ]; then
	echo "[ ERROR ] Specify a file or directory to encrypt."
	exit 1
fi

selected_name=$(basename "$1" | tr . _)

echo "[ ENCRYPT ] Encrypting $1..."
# sudo tar cvzf - "$usb_mountpoint"/Lock-encrypt | pv -ptrb --size "$(du -sb "$usb_mountpoint"/Lock-encrypt | awk '{print $1}')" | sudo gpg --symmetric -o "$usb_mountpoint"/Lock-encrypt.tar.gz.gpg || {
# 	echo "[ ERROR ] Failed to encrypt Lock-encrypt directory."
# 	exit 1
# }
#

tar czf - "$1" | pv | gpg --symmetric -o "$selected_name".tar.gz.gpg || {
	echo "[ ERROR ] Failed to tar and encrypt $1. Try again."
	exit 1
}

echo "[ OPTION ] $1 can be removed."

while true; do
	read -rp " Do you wish to remove it? [Y/n]: " yn_input

	if [[ -z $yn_input ]]; then
		yn_input="y"
	fi

	case $yn_input in
	[Yy]*)
		echo "[ REMOVING ] $1..."
		rm -rf "$1"
		break
		;;
	[Nn]*)
		echo "[ SKIPPING ] $1 will not be removed."
		break
		;;
	*) printf " Error: only write 'y' or 'n'\n\n" ;;
	esac
done

echo "[ SUCCESS ] $selected_name is now ENCRYPTED."
