#!/bin/sh
dir=$(uuidgen | cut -d '-' -f1)
mktemp -d /tmp/$dir
cp $1 /tmp/$dir
zip -r /tmp/$dir.zip /tmp/$dir
zipcloak /tmp/$dir.zip
curl -F"file=@/tmp/$dir.zip" 0x0.st

# to download (use curl or aria2c):
# curl -o gruvlatte.zip "https://0x0.st/HDwg.zip"
# to decrypt/extract (will prompt for password):
# unzip gruvlatte.zip
