#!/usr/bin/env bash

from_sourcedir="$1"
to_destdir="$2"

# store directories in an array
dir_fromsource=()
while IFS= read -r -d '' dir; do
	dir_fromsource+=("$dir")
done < <(find "$from_sourcedir" -type d -print0)

if [ ${#dir_fromsource[@]} -eq 0 ]; then
	echo "Error: No directories found."
	exit 1
fi

echo "Extracting..."

for dir in "${dir_fromsource[@]}"; do
	md_files=()
	while IFS= read -r -d '' file; do
		md_files+=("$file")
	done < <(find "$dir" -type f -name '*.md' -print0)
	if [ ${#md_files[@]} -gt 0 ]; then
		mv "${md_files[@]}" "$to_destdir"
	fi
done

# store empty directories
empty_dirs=()
while IFS= read -r -d '' dir; do
	empty_dirs+=("$dir")
done < <(find "$from_sourcedir" -type d -empty -print0)

if [ ${#empty_dirs[@]} -gt 0 ]; then
	echo "Removing empty directories..."
	rm -rf "${empty_dirs[@]}"
fi

echo "Done!"
