#!/bin/sh

# NOTE: use `lsblk` to identify the correct usbpart (if different then change usbpart value)
# --> i know there are two error handling logic `set -e` and `|| {...; exit 1}`, im just paranoid kek

set -e

mountpoint="/mnt/hdd"
hdd_part="/dev/sda1"

# ensure that the mountpoint exists
if [ ! -d "$mountpoint" ]; then
	# create mountpoint
	echo "[ INFO ] No mountpoint detected.... creating mountpoint at $mountpoint"
	sudo mkdir -p "$mountpoint"
fi

# open with cryptsetup
sudo cryptsetup luksOpen "$hdd_part" sda1 || {
	echo "[ ERROR ] Unable to open device."
	exit 1
}

# mount
sudo mount /dev/mapper/sda1 "$mountpoint" || {
	echo "[ ERROR ] Unable to mount device."
	exit 1
}

echo "[ SUCCESS ] Device mounted at $mountpoint"
notify-send "HDD mounted!"
