#!/bin/sh

# NOTE: This script is for unmounting and encrypting/locking a disk drive.
# --> i know there are two error handling logic `set -e` and `|| {...; exit 1}`, im just paranoid kek

set -e

mountpoint="/mnt/hdd"
# hdd_disk="/dev/sda1"
disk_name="hdd"

# ensure that the mountpoint exists
if [ -d "$mountpoint" ]; then
	# unmount
	sudo umount "$mountpoint" || {
		echo "[ ERROR ] Unable to unmount the device."
		exit 1
	}

	echo "[ INFO ] Device unmounted."
	notify-send "Device unmounted." "$mountpoint has been unmounted."

	# close with cryptsetup (encrypt)
	sudo cryptsetup luksClose "$disk_name" || {
		echo "[ ERROR ] Unable to close the device."
		exit 1
	}

	# sudo eject "$hdd_disk" || {
	# 	echo "[ ERROR ] Unable to eject the device."
	# 	exit 1
	# }

	echo "[ SUCCESS ] 🔒 Device is now ENCRYPTED and LOCKED. "
	notify-send " 🔒 Device is now ENCRYPTED and LOCKED."
fi
