#!/bin/bash

# ,journal is a script similar to my templater template
# for generating journal template from neovim instead of from obsidian

set -e

if [ $# -eq 0 ]; then
	echo "[ ERROR ] No title argument passed/specified. Please try again."
	exit 1
fi

title="$*"
date_title=$(date +%Y%m%d)
final_title="$date_title $title"
new_journal_entry="$VAULT/Personal/Journal/$final_title.md"
date_frontmatter=$(date +%Y-%m-%dT%H:%m)

# check if $VAULT path exists
if [ ! -d "$VAULT" ]; then
	echo "No VAULT env path created. Set a VAULT path in your .zshrc or .bashrc first."
	exit 1
fi

new_journal() {
	touch "$new_journal_entry"
	cat >"$new_journal_entry" <<EOF
---
date: $date_frontmatter
tags: []
---


EOF
}

new_journal

nvim '+ normal Gzz' "$new_journal_entry" -c ":NoNeckPain"
