#!/bin/sh

# TODO: 1: read input with options (sync all or sync specific dirs)
# TODO: 2: add flags support

usb_mountpoint="/mnt/$(whoami)/ejsmain/"
wizardry="$HOME/wizardry/scripts-magic-spells/"
dotfiles="$HOME/dotfiles/scripts-magic-spells/"

set -e

echo "[ SYNCING ] scripts magic spells..."

{
	rsync -auz "$wizardry" "$dotfiles"
	echo "[ CHECKING ] is USB mounted?... "
	if [ -d "$usb_mountpoint" ]; then
		echo "[ SUCCESS ] USB is mounted, now syncing..."
		echo "[ SYNCING ] Scripts / Magic Spells..."
		sudo rsync -auz "$wizardry" "$usb_mountpoint"/scripts-magic-spells/
	else
		echo "[ SKIPPING ] USB is not mounted. Now skipping..."
	fi
} | pv -p --timer --rate --bytes | cat

echo "[ SUCCESS ] Everything perfectly synced!"
