#!/usr/bin/env bash

# local script to sync wizardry/scripts-magic-spells and dotfiles/scripts-magic-spells
# and run every 5 mins (cronjob) */5 * * * *
# test 123
# test 123

set -e

wiz="$HOME/vault/wizardry/scripts-magic-spells"
dot="$HOME/dotfiles/scripts-magic-spells"
src=""
dest=""

if [[ "$*" == "--dry-run" ]]; then
    echo "initializing dry-run..."
    if [[ $(date -r "$wiz" +%s) -gt $(date -r "$dot" +%s) ]]; then
        echo "src is $wiz, dest is $dot"
        src=$wiz
        dest=$(dirname "$dot")
    else
        echo "src is $dot, dest is $wiz"
        src=$dot
        dest=$(dirname "$wiz")
    fi

    echo "src: $src"
    echo "dest: $dest"
    exit 0
fi

if [[ $(date -r "$wiz" +%s) -gt $(date -r "$dot" +%s) ]]; then
    echo "src is $wiz, dest is $dot"
    src=$wiz
    dest=$(dirname "$dot")
else
    echo "src is $dot, dest is $wiz"
    src=$dot
    dest=$(dirname "$wiz")
fi

rsync -azvh --progress "$src" "$dest"
